### PR TITLE
Cuevana3 with "https://cuevana3.one" domain since "https://n2.cuevana3.me" doesnt work

### PR DESCRIPTION
**Pull request by Likver**
Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

**Comment by Quickdesh** [comment]
These have to be some of the best commit names I have seen, 10/10

**Comment by Likver** [comment]
> These have to be some of the best commit names I have seen, 10/10

Sorry, what i mean is that theres another extension that uses https://n2.cuevana3.me but that domain doesn't work, this one uses https://cuevana3.one which, well, works

**Comment by Quickdesh** [comment]
wait wait wait, so the only thing you changed is the url?

**Comment by Likver** [comment]
i dont know what to reply, i tried to use git for more than 5h just to upload shitty files and nows when i realize that, i just cant believe it, im sorry, im going to do that right now

**Comment by Quickdesh** [comment]
Oof, it's all good m8. You are learning and that's the main focus now :).

**Comment by jmir1** [comment]
Good luck!!! 😂

**Pull request closed without merging**
