### PR TITLE
Ennovelas fixes

### LINKED ISSUE #1361: {bug} EnNovelas changed their main domain.
### Source information and language

EnNovelas 13.1 doesn't load anymore

### Steps to reproduce

1. Install EnNovelas extension
2. Try to play any video
Doesn't load

### Expected behavior

It was working just fine some days ago.

### Actual behavior

I tried with a lot of different videos, before clicking on their icon website within aniyomi and realising they just changed their domain.

### Aniyomi version

0.12.3.10

### Android version

Android 10

### Other details

They just changed their website, I guess that's why the extension doesn't work anymore.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/jmir1/aniyomi/releases/latest)**
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/jmir1/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by imper1aldev**
Checklist:

Closes #1361

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

**Comment by imper1aldev** [comment]
@jmir1 Admin please close issue #1361 , thanks

**Comment by jmir1** [comment]
> @jmir1 Admin please close issue #1361 , thanks

Pro tip: Put "closes #1361" into your PR description, then it will be automatically closed when this PR is merged.

**Comment by Samfun75** [comment]
> * [x]  Referenced all related issues in the PR body (e.g. "Closes #xyz")

:)

**Comment by imper1aldev** [comment]
> > @jmir1 Admin please close issue #1361 , thanks
> 
> Pro tip: Put "closes #1361" into your PR description, then it will be automatically closed when this PR is merged.

I just added it to the description, thanks 👍

**Pull request merged**
