### PR TITLE
vidembed: fix next/prev not working

### PR DESCRIPTION
**Pull request by GouravShDev**
Fixed next/prev not working in the Video player in Vidembed extension. 
Cause: Wrong episode number while parsing episodes.

### CODE REVIEW

**Review by jmir1 — CHANGES_REQUESTED** [review]
i feel like you should add a line like
`episode.episode_number = ep.toFloat()`
(but try to catch numberformat errors)

**Comment by GouravShDev** [comment]
Yeah, it can be used. But not all shows contain episode numbers some contain "episode special" instead of a number Like: https://vidembed.io/videos/the-kings-of-napa-season-1-episode-special-preview. 
Should I just return 0 in that case?

**Comment by jmir1** [comment]
yeah you can do that.

**Comment by GouravShDev** [comment]
done

**Review by jmir1 — APPROVED** [review]

**Pull request merged**
