### PR TITLE
Add Extension: AllAnime

### LINKED ISSUE #889: [Source Request] <Allanime.site>
## Source website
- Name: Allanime
- Link: https://allanime.site
- Language(s): English, Japanese.

### PR DESCRIPTION
**Pull request by Secozzi**
Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Have tested the modifications by compiling and running the extension through Android Studio

Closes #889

### CODE REVIEW

**Comment by Samfun75** [comment]
You should use the extractor libs available in https://github.com/jmir1/aniyomi-extensions/tree/master/lib so that the extension is updated when there is a fix

**Comment by Samfun75** [comment]
Okru also has a lib.

**Comment by Secozzi** [comment]
🤦

**Comment by Secozzi** [comment]
For some anime, such as Kage no Jitsuryokusha ni Naritakute, the Okru extractor seems to be broken. I will attempt to rewrite it later

**Pull request merged**
