### PR TITLE
Added preferred server Option

### PR DESCRIPTION
**Pull request by Abhishek890**
Checklist:
 - [x] Updated extVersionCode value in build.gradle for individual extensions
- [x] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

**Comment by Secozzi** [comment]
You need to update the video sorting as well so the preferred server comes on top

**Comment by Abhishek890** [comment]
> 

ok will do it

**Comment by Abhishek890** [comment]
@Secozzi  fixed now sorting is working fine checked and tested

**Comment by Abhishek890** [comment]
@jmir1 review it and merge

**Comment by jmir1** [comment]
Don't ping me please I will look at it wherever I get the time

**Pull request merged**
