### PR TITLE
Updated domain urls

### PR DESCRIPTION
**Pull request by givemyusd**
Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

**Review by jmir1 — CHANGES_REQUESTED** [review]
please update the version codes in the build.gradle files.

**Comment by Secozzi** [comment]
Since this doesn't actually change anything in the extension (to the end user), shouldn't CI just be skipped instead of updating version?

**Comment by givemyusd** [comment]
> please update the version codes in the build.gradle files.

Done 👍

**Comment by jmir1** [comment]
> Since this doesn't actually change anything in the extension (to the end user), shouldn't CI just be skipped instead of updating version?

If you've never opened the extension settings then the default value is used, so it does change the behaviour for some people.

**Review by jmir1 — APPROVED** [review]

**Pull request merged**
